sudo: required

services:
  - docker

before_install:
  - docker build -t scott:sample-ui -f Dockerfile.dev .

script:
  - docker run -e CI=true scott:sample-ui npm run test
 
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: sample-ui
  env: dev
  bucket_name: dev-deployment
  bucket_path: sample-ui
  on:
    branch: main
  access_key_id: $AWS_KEY
  secret_access_key:
    secure: "$AWS_SECRET"
